version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "test"
    groups:
      python-dependencies:
        patterns:
          - "*"
