# Generated by Django 3.2.5 on 2021-07-28 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35, unique=True, verbose_name='Tags')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Book Title')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden from search results')),
                ('authors', models.ManyToManyField(related_name='books', to='books.Author')),
                ('tags', models.ManyToManyField(to='books.Tag', verbose_name='tags')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(choices=[('a', 'Ansfield-Wolf'), ('b', "Buckeye Children's & Teen"), ('c', 'Choose to Read Ohio'), ('d', 'Dayton Literary Peace Prize'), ('f', "Floyd's Pick"), ('j', 'James Cook'), ('n', 'Norman A. Sugarman'), ('o', 'Ohioana'), ('t', 'Thurber Prize')], max_length=75)),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Invalid date'), django.core.validators.MaxValueValidator(2022, message='Invalid date')])),
                ('prize', models.CharField(choices=[('c', 'Featured Title'), ('f', 'Finalist'), ('h', 'Honor'), ('m', 'Honorable Mention'), ('n', 'Nominee'), ('r', 'Runner-Up'), ('s', 'Special Honor'), ('w', 'Winner')], max_length=1, verbose_name='Prize')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden from search results')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='books.book')),
            ],
            options={
                'ordering': ['award', '-year'],
            },
        ),
    ]
