# Generated by Django 5.2.6 on 2025-09-22 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award',
            field=models.CharField(choices=[('a', 'Ansfield-Wolf'), ('p', 'Arnold Adoff'), ('b', "Buckeye Children's & Teen"), ('c', 'Choose to Read Ohio'), ('d', 'Dayton Literary Peace Prize'), ('f', "Floyd's Pick"), ('j', 'James Cook'), ('m', 'Nancy Dasher Book Awards'), ('n', 'Norman A. Sugarman'), ('o', 'Ohio Book Award'), ('s', "Scott O'Dell"), ('t', 'Thurber Prize')], max_length=75),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Invalid date'), django.core.validators.MaxValueValidator(2026, message='Invalid date')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=55, unique=True, verbose_name='Tags'),
        ),
    ]
