name: Build and deploy Python app to Azure Web App - lib-test-cobaa-as

on:
  push:
    branches:
      - test
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Cairo dependencies
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev pkg-config

      - name: Set up Python version
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: python-app
          path: .

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'lib-test-cobaa-as'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4AEB796096140BE98E1CAF2BDAF4028 }}
